import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConsentManagerProvider, CookieBanner, ConsentManagerDialog } from "@c15t/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
    		<ConsentManagerProvider options={{
    				mode: 'offline',
    				consentCategories: ['necessary', 'marketing'], // Optional: Specify which consent categories to show in the banner. 
    			}}>
    			<CookieBanner />
    			<ConsentManagerDialog />
    			
            {children}
          
    		</ConsentManagerProvider>
    	</body>
        </html>
      )
}
